-- Türkiye Şehir ve İlçe Verileri
-- Bu SQL kodunu MySQL'de çalıştırarak tüm şehir ve ilçeleri ekleyebilirsiniz

-- Önce mevcut verileri temizle (isteğe bağlı)
-- DELETE FROM Districts;
-- DELETE FROM Cities;

-- Şehirleri ekle
INSERT INTO Cities (Name, CreatedDate) VALUES
('Adana', CURRENT_TIMESTAMP),
('Adıyaman', CURRENT_TIMESTAMP),
('Afyonkarahisar', CURRENT_TIMESTAMP),
('Ağrı', CURRENT_TIMESTAMP),
('Amasya', CURRENT_TIMESTAMP),
('Ankara', CURRENT_TIMESTAMP),
('Antalya', CURRENT_TIMESTAMP),
('Artvin', CURRENT_TIMESTAMP),
('Aydın', CURRENT_TIMESTAMP),
('Balıkesir', CURRENT_TIMESTAMP),
('Bilecik', CURRENT_TIMESTAMP),
('Bingöl', CURRENT_TIMESTAMP),
('Bitlis', CURRENT_TIMESTAMP),
('Bolu', CURRENT_TIMESTAMP),
('Burdur', CURRENT_TIMESTAMP),
('Bursa', CURRENT_TIMESTAMP),
('Çanakkale', CURRENT_TIMESTAMP),
('Çankırı', CURRENT_TIMESTAMP),
('Çorum', CURRENT_TIMESTAMP),
('Denizli', CURRENT_TIMESTAMP),
('Diyarbakır', CURRENT_TIMESTAMP),
('Edirne', CURRENT_TIMESTAMP),
('Elazığ', CURRENT_TIMESTAMP),
('Erzincan', CURRENT_TIMESTAMP),
('Erzurum', CURRENT_TIMESTAMP),
('Eskişehir', CURRENT_TIMESTAMP),
('Gaziantep', CURRENT_TIMESTAMP),
('Giresun', CURRENT_TIMESTAMP),
('Gümüşhane', CURRENT_TIMESTAMP),
('Hakkâri', CURRENT_TIMESTAMP),
('Hatay', CURRENT_TIMESTAMP),
('Isparta', CURRENT_TIMESTAMP),
('Mersin', CURRENT_TIMESTAMP),
('İstanbul', CURRENT_TIMESTAMP),
('İzmir', CURRENT_TIMESTAMP),
('Kars', CURRENT_TIMESTAMP),
('Kastamonu', CURRENT_TIMESTAMP),
('Kayseri', CURRENT_TIMESTAMP),
('Kırklareli', CURRENT_TIMESTAMP),
('Kırşehir', CURRENT_TIMESTAMP),
('Kocaeli', CURRENT_TIMESTAMP),
('Konya', CURRENT_TIMESTAMP),
('Kütahya', CURRENT_TIMESTAMP),
('Malatya', CURRENT_TIMESTAMP),
('Manisa', CURRENT_TIMESTAMP),
('Kahramanmaraş', CURRENT_TIMESTAMP),
('Mardin', CURRENT_TIMESTAMP),
('Muğla', CURRENT_TIMESTAMP),
('Muş', CURRENT_TIMESTAMP),
('Nevşehir', CURRENT_TIMESTAMP),
('Niğde', CURRENT_TIMESTAMP),
('Ordu', CURRENT_TIMESTAMP),
('Rize', CURRENT_TIMESTAMP),
('Sakarya', CURRENT_TIMESTAMP),
('Samsun', CURRENT_TIMESTAMP),
('Siirt', CURRENT_TIMESTAMP),
('Sinop', CURRENT_TIMESTAMP),
('Sivas', CURRENT_TIMESTAMP),
('Tekirdağ', CURRENT_TIMESTAMP),
('Tokat', CURRENT_TIMESTAMP),
('Trabzon', CURRENT_TIMESTAMP),
('Tunceli', CURRENT_TIMESTAMP),
('Şanlıurfa', CURRENT_TIMESTAMP),
('Uşak', CURRENT_TIMESTAMP),
('Van', CURRENT_TIMESTAMP),
('Yozgat', CURRENT_TIMESTAMP),
('Zonguldak', CURRENT_TIMESTAMP),
('Aksaray', CURRENT_TIMESTAMP),
('Bayburt', CURRENT_TIMESTAMP),
('Karaman', CURRENT_TIMESTAMP),
('Kırıkkale', CURRENT_TIMESTAMP),
('Batman', CURRENT_TIMESTAMP),
('Şırnak', CURRENT_TIMESTAMP),
('Bartın', CURRENT_TIMESTAMP),
('Ardahan', CURRENT_TIMESTAMP),
('Iğdır', CURRENT_TIMESTAMP),
('Yalova', CURRENT_TIMESTAMP),
('Karabük', CURRENT_TIMESTAMP),
('Kilis', CURRENT_TIMESTAMP),
('Osmaniye', CURRENT_TIMESTAMP),
('Düzce', CURRENT_TIMESTAMP);

-- İlçeleri ekle (her şehir için önemli ilçeler)
-- Adana
INSERT INTO Districts (Name, CityId, CreatedDate) VALUES
('Seyhan', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Yüreğir', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Çukurova', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Sarıçam', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Karaisalı', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Aladağ', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Ceyhan', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Feke', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('İmamoğlu', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Karataş', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Kozan', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Pozantı', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Saimbeyli', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Tufanbeyli', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP),
('Yumurtalık', (SELECT Id FROM Cities WHERE Name = 'Adana'), CURRENT_TIMESTAMP);

-- Ankara
INSERT INTO Districts (Name, CityId, CreatedDate) VALUES
('Çankaya', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Keçiören', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Yenimahalle', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Mamak', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Sincan', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Altındağ', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Etimesgut', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Gölbaşı', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Pursaklar', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Akyurt', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Ayaş', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Bala', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Beypazarı', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Çamlıdere', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Çubuk', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Elmadağ', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Evren', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Güdül', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Haymana', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Kalecik', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Kazan', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Kızılcahamam', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Nallıhan', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Polatlı', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP),
('Şereflikoçhisar', (SELECT Id FROM Cities WHERE Name = 'Ankara'), CURRENT_TIMESTAMP);

-- İstanbul
INSERT INTO Districts (Name, CityId, CreatedDate) VALUES
('Adalar', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Arnavutköy', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Ataşehir', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Avcılar', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Bağcılar', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Bahçelievler', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Bakırköy', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Başakşehir', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Bayrampaşa', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Beşiktaş', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Beykoz', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Beylikdüzü', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Beyoğlu', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Büyükçekmece', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Çatalca', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Çekmeköy', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Esenler', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Esenyurt', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Eyüpsultan', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Fatih', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Gaziosmanpaşa', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Güngören', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Kadıköy', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Kağıthane', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Kartal', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Küçükçekmece', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Maltepe', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Pendik', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Sancaktepe', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Sarıyer', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Silivri', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Sultanbeyli', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Sultangazi', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Şile', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Şişli', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Tuzla', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Ümraniye', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Üsküdar', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP),
('Zeytinburnu', (SELECT Id FROM Cities WHERE Name = 'İstanbul'), CURRENT_TIMESTAMP);

-- İzmir
INSERT INTO Districts (Name, CityId, CreatedDate) VALUES
('Aliağa', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Balçova', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Bayındır', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Bayraklı', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Bergama', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Beydağ', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Bornova', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Buca', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Çeşme', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Çiğli', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Dikili', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Foça', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Gaziemir', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Güzelbahçe', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Karabağlar', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Karaburun', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Karşıyaka', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Kemalpaşa', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Kınık', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Kiraz', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Konak', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Menderes', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Menemen', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Narlıdere', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Ödemiş', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Seferihisar', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Selçuk', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Tire', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Torbalı', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP),
('Urla', (SELECT Id FROM Cities WHERE Name = 'İzmir'), CURRENT_TIMESTAMP);

-- Antalya
INSERT INTO Districts (Name, CityId, CreatedDate) VALUES
('Akseki', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Aksu', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Alanya', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Demre', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Döşemealtı', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Elmalı', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Finike', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Gazipaşa', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Gündoğmuş', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('İbradı', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Kaş', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Kemer', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Kepez', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Konyaaltı', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Korkuteli', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Kumluca', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Manavgat', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Muratpaşa', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP),
('Serik', (SELECT Id FROM Cities WHERE Name = 'Antalya'), CURRENT_TIMESTAMP);

-- Bursa
INSERT INTO Districts (Name, CityId, CreatedDate) VALUES
('Büyükorhan', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Gemlik', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Gürsu', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Harmancık', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('İnegöl', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('İznik', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Karacabey', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Keles', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Kestel', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Mudanya', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Mustafakemalpaşa', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Nilüfer', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Orhaneli', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Orhangazi', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Osmangazi', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Yenişehir', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP),
('Yıldırım', (SELECT Id FROM Cities WHERE Name = 'Bursa'), CURRENT_TIMESTAMP);

-- Gaziantep
INSERT INTO Districts (Name, CityId, CreatedDate) VALUES
('Araban', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP),
('İslahiye', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP),
('Karkamış', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP),
('Nizip', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP),
('Nurdağı', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP),
('Oğuzeli', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP),
('Şahinbey', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP),
('Şehitkamil', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP),
('Yavuzeli', (SELECT Id FROM Cities WHERE Name = 'Gaziantep'), CURRENT_TIMESTAMP);

-- Konya
INSERT INTO Districts (Name, CityId, CreatedDate) VALUES
('Ahırlı', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Akören', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Akşehir', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Altınekin', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Beyşehir', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Bozkır', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Cihanbeyli', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Çeltik', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Çumra', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Derbent', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Derebucak', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Doğanhisar', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Emirgazi', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Ereğli', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Güneysinir', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Hadim', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Halkapınar', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Hüyük', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Ilgın', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Kadınhanı', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Karapınar', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Karatay', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Kulu', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Meram', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Sarayönü', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Selçuklu', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Seydişehir', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Taşkent', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Tuzlukçu', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Yalıhüyük', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP),
('Yunak', (SELECT Id FROM Cities WHERE Name = 'Konya'), CURRENT_TIMESTAMP);

-- Diğer önemli şehirler için de ilçeler eklenebilir...
-- Bu örnekte en büyük şehirlerin ilçelerini ekledim
-- İhtiyacınıza göre diğer şehirlerin ilçelerini de ekleyebilirsiniz

-- Veri kontrolü
SELECT 
    c.Name as 'Şehir',
    COUNT(d.Id) as 'İlçe Sayısı'
FROM Cities c
LEFT JOIN Districts d ON c.Id = d.CityId
GROUP BY c.Id, c.Name
ORDER BY COUNT(d.Id) DESC;
